version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev --host 0.0.0.0
