import {
  Heart,
  Laptop,
  Gift,
  Clock,
  GraduationCap,
  Users,
  Pizza,
  Bike,
  TrendingUp,
  Car,
  Home,
  Briefcase,
  Shield,
  Star,
  Coffee,
  Music,
  Camera,
  Gamepad2,
  Plane,
  MapPin,
  Phone,
  Mail,
  Calendar,
  BookOpen,
  Lightbulb,
  Target,
  Award,
  Zap,
  Leaf,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  Snowflake,
  Flame,
  Droplets,
  Mountain,
  Trees,
  Fish,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Turtle,
  FlowerIcon as Butterfly,
  Flower,
  Apple,
  Banana,
  Cherry,
  Grape,
  CherryIcon as Strawberry,
  Carrot,
  SproutIcon as Broccoli,
  CroissantIcon as Bread,
  Cake,
  IceCream,
  Wine,
  Beer,
  Martini,
  Utensils,
  ShoppingCart,
  CreditCard,
  Wallet,
  Coins,
  DollarSign,
  TrendingDown,
  BarChart,
  PieChart,
  Activity,
  Wifi,
  Bluetooth,
  Battery,
  Smartphone,
  Monitor,
  Keyboard,
  Mouse,
  Headphones,
  Speaker,
  Mic,
  Video,
  Image,
  FileText,
  Folder,
  Download,
  Upload,
  Share,
  Link,
  Lock,
  Unlock,
  Key,
  Settings,
  PenToolIcon as Tool,
  Wrench,
  Hammer,
  Scissors,
  Paintbrush,
  Palette,
  Brush,
  Pen,
  Pencil,
  Calculator,
  Globe,
  Compass,
  Map,
  Navigation,
  Anchor,
  Ship,
  Truck,
  Bus,
  Train,
  Rocket,
  BirdIcon as Helicopter,
  FlagIcon as Parachute,
  Tent,
  Backpack,
  Luggage,
  Ticket,
  Trophy,
  Medal,
  Crown,
  Diamond,
  Gem,
  BellRingIcon as Ring,
  Watch,
  Glasses,
  Shirt,
  FootprintsIcon as Shoe,
  UmbrellaIcon as UmbrellaBeach,
  HardHatIcon as Hat,
  ChefHatIcon,
} from "lucide-react"
import { JSX } from "react"

export const iconMap: Record<string, JSX.Element> = {
  // Original icons
  heart: <Heart />,
  laptop: <Laptop />,
  gift: <Gift />,
  clock: <Clock />,
  "graduation-cap": <GraduationCap />,
  users: <Users />,
  pizza: <Pizza />,
  bike: <Bike />,
  "trending-up": <TrendingUp />,

  // Transportation
  car: <Car />,
  plane: <Plane />,
  ship: <Ship />,
  truck: <Truck />,
  bus: <Bus />,
  train: <Train />,
  rocket: <Rocket />,
  helicopter: <Helicopter />,

  // Home & Living
  home: <Home />,
  briefcase: <Briefcase />,
  shield: <Shield />,
  star: <Star />,
  coffee: <Coffee />,

  // Entertainment
  music: <Music />,
  camera: <Camera />,
  gamepad: <Gamepad2 />,
  video: <Video />,
  headphones: <Headphones />,
  speaker: <Speaker />,

  // Communication
  phone: <Phone />,
  mail: <Mail />,
  calendar: <Calendar />,
  share: <Share />,
  link: <Link />,

  // Education & Work
  "book-open": <BookOpen />,
  lightbulb: <Lightbulb />,
  target: <Target />,
  award: <Award />,
  trophy: <Trophy />,
  medal: <Medal />,
  crown: <Crown />,

  // Nature & Weather
  sun: <Sun />,
  moon: <Moon />,
  cloud: <Cloud />,
  umbrella: <Umbrella />,
  snowflake: <Snowflake />,
  flame: <Flame />,
  droplets: <Droplets />,
  leaf: <Leaf />,
  mountain: <Mountain />,
  trees: <Trees />,
  flower: <Flower />,

  // Animals
  fish: <Fish />,
  bird: <Bird />,
  cat: <Cat />,
  dog: <Dog />,
  rabbit: <Rabbit />,
  turtle: <Turtle />,
  butterfly: <Butterfly />,

  // Food & Drink
  apple: <Apple />,
  banana: <Banana />,
  cherry: <Cherry />,
  grape: <Grape />,
  strawberry: <Strawberry />,
  carrot: <Carrot />,
  broccoli: <Broccoli />,
  bread: <Bread />,
  cake: <Cake />,
  "ice-cream": <IceCream />,
  wine: <Wine />,
  beer: <Beer />,
  martini: <Martini />,
  utensils: <Utensils />,
  "chef-hat": <ChefHatIcon />,

  // Finance
  "shopping-cart": <ShoppingCart />,
  "credit-card": <CreditCard />,
  wallet: <Wallet />,
  coins: <Coins />,
  "dollar-sign": <DollarSign />,
  "trending-down": <TrendingDown />,
  "bar-chart": <BarChart />,
  "pie-chart": <PieChart />,

  // Technology
  wifi: <Wifi />,
  bluetooth: <Bluetooth />,
  battery: <Battery />,
  smartphone: <Smartphone />,
  monitor: <Monitor />,
  keyboard: <Keyboard />,
  mouse: <Mouse />,
  mic: <Mic />,

  // Tools & Utilities
  settings: <Settings />,
  tool: <Tool />,
  wrench: <Wrench />,
  hammer: <Hammer />,
  scissors: <Scissors />,
  paintbrush: <Paintbrush />,
  palette: <Palette />,
  brush: <Brush />,
  pen: <Pen />,
  pencil: <Pencil />,
  calculator: <Calculator />,

  // Security
  lock: <Lock />,
  unlock: <Unlock />,
  key: <Key />,

  // Navigation & Location
  globe: <Globe />,
  compass: <Compass />,
  map: <Map />,
  navigation: <Navigation />,
  "map-pin": <MapPin />,

  // Fashion & Accessories
  diamond: <Diamond />,
  gem: <Gem />,
  ring: <Ring />,
  watch: <Watch />,
  glasses: <Glasses />,
  hat: <Hat />,
  shirt: <Shirt />,
  shoe: <Shoe />,

  // Travel & Adventure
  tent: <Tent />,
  backpack: <Backpack />,
  luggage: <Luggage />,
  ticket: <Ticket />,
  parachute: <Parachute />,
  anchor: <Anchor />,
  "umbrella-beach": <UmbrellaBeach />,

  // Files & Data
  "file-text": <FileText />,
  folder: <Folder />,
  download: <Download />,
  upload: <Upload />,
  image: <Image />,

  // Energy & Power
  zap: <Zap />,
  activity: <Activity />,
}
